### ISSUE TITLE
No spinner named 'xxx' is registered.

### ISSUE THREAD

**Issue by yorraksahb** [Chevtek/angular-spinners#1] opened 2015-06-18 10:50 UTC
This is more of a question, I integrated your spinner as per the readme. But when i try to run the app, it says that the spinner is not registered.

**Comment by AlexAllocated** [comment] 2015-06-19 00:08
You will have to share some of your code so I can help you identify the issue. You have a spinner directive on the page with a name attribute, yes?

**Comment by AlexAllocated** [comment] 2015-06-23 17:37
I'm closing this for now. Please re-open if you're still having issues and want to provide additional details. You can refer to [this working demo](http://codepen.io/Chevex/pen/VLzVbb) if you just need a simple example.

**Closed as completed by AlexAllocated** 2015-06-23 17:37 UTC

**Comment by xescuder** [comment] 2015-07-01 18:25
I've the same problem. Any suggestion?

**Comment by AlexAllocated** [comment] 2015-07-01 18:29
You guys will really need to share some of your code for me to help you. The best place though is probably stackoverflow because this is an implementation bug, not a bug with the library. You are trying to hide/show a spinner that hasn't registered yet. Check out the `onLoaded` attribute in the README :)

**Comment by AlexAllocated** [comment] 2015-07-01 19:21
@yorraksahb and @xescuder I don't know your specific use-cases, but I know the common pitfall is when you try to immediately show a spinner from within your controller and that spinner is nested _inside_ the element the controller is attached to.

I went ahead and put together a FAQ section in the README. The first question in that section is this one and the answer links to another issue I created to explain the problem in detail.

[Here it is :)](https://github.com/codetunnel/angular-spinners/issues/4)

I hope that helps!

**Comment by xescuder** [comment] 2015-07-01 20:08
Thanks. Well explained! Now it works!

**Comment by RabbitNinja** [comment] 2016-05-23 14:50
The spinner directive works great if the < spinner > tag is located in the main html. I'm running into an issue to load the spinner correctly when I place the < spinner > tag into a modal popup, where the html template is located in a different file. The error message I got was "No spinner named 'spinner' is registered." Is there a work around to this? Thanks!
